### ISSUE TITLE
Latest version not on flathub

### ISSUE THREAD

**Issue by zaclegarssure** [flathub/io.gitlab.persiangolf.voicegen#2]
Apparently the latest version (the one where the filesystem=host permission was removed) has not been build and published by the buildbot, it didn't start in the first place. 
If you download the latest version and run `flatpak info --show-permissions io.gitlab.persiangolf.voicegen` it will still have access to the host filesystem.
Maybe this is because the changes were only in the `finish-args` section, and the bot is configured such that it won't do the build thinking nothing relevant changed. Or maybe this happened because two commit were too closed from each other, I don't know.
Regardless of the reason, someone should re-run the build if it is possible.

**Comment by Ma5t3rful** [comment]
@zaclegarssure  I just updated the app with new permissions.
mine seems ok now:
```
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
devices=dri;
filesystems=xdg-config/kdeglobals:ro;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk
org.kde.kconfig.notify=talk
org.kde.KGlobalSettings=talk

```
could you please check it on your system? Thanks.

**Comment by FreeFight3r** [comment]
I checked the permissions. there is no `host` permission in the new version.

**Comment by Ma5t3rful** [comment]
Thanks, @FreeFight3r.
