### ISSUE TITLE
Do i need <description> for every release in my appdata?

### ISSUE THREAD

**Issue by Ma5t3rful** [flathub/io.gitlab.persiangolf.voicegen#3]
Do i strictly need `<description>` for every `<release>` in my appdata? or i can skip it?

@pizzadude

**Comment by pizzadude** [comment]
I don't know, ask the Flathub maintainers on https://discourse.flathub.org/ or on Matrix.

**Comment by Ma5t3rful** [comment]
[No](https://discourse.flathub.org/t/do-i-strictly-need-description-for-every-release-in-my-appdata-or-i-can-skip-it/2650). It is optional
