### ISSUE TITLE
App Licence

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/io.gitlab.persiangolf.voicegen#5]
Hi. Thanks for packaging this app as a flatpak and publishing on Flathub.

I wanted to point out that the Flathub page says it's proprietary but the Gitlab page has the GNU GPL in the LICENCE.md file...?

**Comment by Ma5t3rful** [comment]
@RasheedAZ 
I don't know whats wrong with it 
@pizzadude What is going on with flathub i just updated this software and new release not popping up in flathub. I validated my appstream file and it looks ok. also the above issue😵‍💫 
![Screenshot_20230909_131042](https://github.com/flathub/io.gitlab.persiangolf.voicegen/assets/37829730/44cfc3ea-fe92-4598-b582-f35d7cc3e819)
![Screenshot_20230909_131209](https://github.com/flathub/io.gitlab.persiangolf.voicegen/assets/37829730/4b157a71-f5bb-4a33-bf88-a96d5179b58e)

**Comment by RasheedAZ** [comment]
I'm seeing incorrect proprietary label on many open source app listings now.

**Comment by Ma5t3rful** [comment]
@RasheedAZ I think it got fixed by itself (not the version issue). can you verify?

**Comment by RasheedAZ** [comment]
Yes showing GPL now

**Comment by Ma5t3rful** [comment]
Ok I'm gonna close this issue and make another one for the other issue.
