### ISSUE TITLE
My update didn't show up 

### ISSUE THREAD

**Issue by Ma5t3rful** [flathub/io.gitlab.persiangolf.voicegen#6]
@barthalion  @hfiguiere  @pizzadude What is going on with flathub? I just updated this software and new release not popping up in flathub! I validated my appstream file and it looks ok. 😵‍💫

**Comment by barthalion** [comment]
```
~ ❱ flatpak remote-info --user --log flathub io.gitlab.persiangolf.voicegen
        ID: io.gitlab.persiangolf.voicegen
       Ref: app/io.gitlab.persiangolf.voicegen/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 105.1 MB
 Installed: 246.7 MB
   Runtime: org.kde.Platform/x86_64/5.15-21.08
       Sdk: org.kde.Sdk/x86_64/5.15-21.08

    Commit: 29c56f8a0df64458f20ad3a38c2d638a4a63afe1d644c943fc36b66b28b0ecd5
    Parent: 8a6bb456564da1b803ce9d9824fe4114d4eb2803782187218fa9063d63e6afbf
   Subject: 2.0.0 (502ead9b)
      Date: 2023-09-07 14:45:02 +0000
```

Your build has been successfully published. If the version on the website is outdated, it means your appdata/metainfo file is wrong.

**Comment by barthalion** [comment]
https://github.com/flathub/io.gitlab.persiangolf.voicegen/blob/master/io.gitlab.persiangolf.voicegen.yml#L71

This still points to 1.6.4.

**Comment by Ma5t3rful** [comment]
> https://github.com/flathub/io.gitlab.persiangolf.voicegen/blob/master/io.gitlab.persiangolf.voicegen.yml#L71
> 
> This still points to 1.6.4.

Thank You so much. That was the issue
